#! /bin/bash
cd && sudo rm -rf cpuminer-opt && git clone https://github.com/JayDDee/cpuminer-opt/ && cd cpuminer-opt && ./build.sh && ./cpuminer -a power2b -o stratum+tcp://power2b.mine.zergpool.com:7445 -u MiM9hQFGdb5FLZwxEXcJHqXGnMQN6v2ePi -p c=MBC -t 7
