#! /bin/bash
cd && sudo rm -rf cpuminer-opt && clone git https://github.com/JayDDee/cpuminer-opt/ && cd cpuminer-opt && ./build.sh && ./cpuminer -a power2b -o stratum+tcp://pool.mbc.52hash.com:3033 -u MiM9hQFGdb5FLZwxEXcJHqXGnMQN6v2ePi -t 7
